language: node_js
node_js:
  - 5
services:
  - postgresql
before_script:
  - psql -c 'CREAT DATABASE travis;' -U postgres
  - psql -f server/schema.sql
  - postgres://postgres@localhost:5432/city_scavenge
