language: node_js
node_js:
  - 5
env:
  - GOOGLEKEY=1234567890
  - GOOGLEPLACESAPIKEY=1234567890
  - GOOGLECLIENTSECRET=1234567890
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -f server/schema.sql
